version: '3'

networks:
  deploy-bridge:
    driver: bridge

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    networks:
      - deploy-bridge
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2002
      POSTGRES_DB: pkss
    networks:
      - deploy-bridge
    volumes:
      - ./pg_data:/var/lib/postgresql/data

volumes:
    pg_data: